
#ifndef _APA_MODULE_ID_
#define _APA_MODULE_ID_

typedef enum {
    APA_MODULE_ID_PSD_FUSION,
    APA_MODULE_ID_PSD_RELOCATE,
    APA_MODULE_ID_IMAGE_PROCESS,
    APA_MODULE_ID_IMAGE_PROCESS_OVX,
    APA_MODULE_ID_APA_EVENT,
    APA_MODULE_ID_APA_COMMON_LIB,
    APA_MODULE_ID_APA_CONTROL,
    APA_MODULE_ID_CALIBRATEDATALIB,
    APA_MODULE_ID_CANBUS_LIB,
    APA_MODULE_ID_CAMERA_LIB,
    APA_MODULE_ID_PSD_SONAR,
    APA_MODULE_ID_PSD_VISION_PATAC,
    APA_MODULE_ID_PSD_VISION_IAUTO,
    APA_MODULE_ID_EVENT_SYSTEM,
    APA_MODULE_ID_CANBUS_PLAYBACK,
    APA_MODULE_ID_PSD_VISION_POSTPROC,
    APA_MODULE_ID_VFUSION,
    APA_MODULE_ID_OD,
    APA_MODULE_ID_FS,
    APA_MODULE_ID_FRAMEWORK_BASE,
    APA_MODULE_ID_FRAMEWORK_CANBUS,
    APA_MODULE_ID_FRAMEWORK_CAMERA,
    APA_MODULE_ID_FRAMEWORK_DETECT,
    APA_MODULE_ID_FRAMEWORK_FUSION,
    APA_MODULE_ID_FRAMEWORK_DR,
    APA_MODULE_ID_FRAMEWORK_APA_APP,
    APA_MODULE_ID_FRAMEWORK_DEMO,
    APA_MODULE_ID_MAX
}APA_MODULE_ID;

typedef enum {
    APA_ERRORCODE_BASE_PSD_FUSION = 0x00010000,
    APA_ERRORCODE_BASE_PSD_RELOCATE = 0x00020000,
    APA_ERRORCODE_BASE_IMAGE_PROCESS = 0x00030000,
    APA_ERRORCODE_BASE_IMAGE_PROCESS_OVX = 0x00040000,
    APA_ERRORCODE_BASE_APA_EVENT = 0x00050000,
    APA_ERRORCODE_BASE_APA_COMMON_LIB = 0x00060000,
    APA_ERRORCODE_BASE_APA_CONTROL = 0x00070000,
    APA_ERRORCODE_BASE_CALIBRATEDATALIB = 0x00080000,
    APA_ERRORCODE_BASE_CANBUS_LIB = 0x00090000,
    APA_ERRORCODE_BASE_CAMERA_LIB = 0x000A0000,
    APA_ERRORCODE_BASE_PSD_SONAR = 0x000B0000,
    APA_ERRORCODE_BASE_PSD_VISION_PATAC = 0x000C0000,
    APA_ERRORCODE_BASE_PSD_VISION_IAUTO = 0x000D0000,
    APA_ERRORCODE_BASE_EVENT_SYSTEM = 0x000E0000,
    APA_ERRORCODE_BASE_CANBUS_PLAYBACK = 0x000F0000,
    APA_ERRORCODE_BASE_PSD_VISION_POSTPROC = 0x00100000,
    APA_ERRORCODE_BASE_VFUSION = 0x00110000,
    APA_ERRORCODE_BASE_OD = 0x00120000,
    APA_ERRORCODE_BASE_FS = 0x00130000,
    APA_ERRORCODE_BASE_FRAMEWORK_CANBUS = 0x00140000,
    APA_ERRORCODE_BASE_FRAMEWORK_CAMERA = 0x00150000,
    APA_ERRORCODE_BASE_FRAMEWORK_DETECT = 0x00160000,
    APA_ERRORCODE_BASE_FRAMEWORK_FUSION = 0x00170000,
    APA_ERRORCODE_BASE_FRAMEWORK_DR = 0x00180000,
    APA_ERRORCODE_BASE_FRAMEWORK_APA_APP = 0x00190000,
    APA_ERRORCODE_BASE_FRAMEWORK_DEMO = 0x001a0000,

}APA_ERRORCODE_BASE;

#endif
